cf:
  1.4.0:
    upgrades_from:
      - 1.3.0
      - 1.3.1
      - 1.3.2
      - 1.3.3
      - 1.3.4
      - 1.3.5
  1.4.1:
    upgrades_from:
      - 1.3.3
      - 1.3.4
      - 1.3.5
      - 1.4.0
  1.4.2:
    upgrades_from:
      - 1.3.3
      - 1.3.4
      - 1.3.5
      - 1.4.0
      - 1.4.1
  1.4.3:
    upgrades_from:
      - 1.3.3
      - 1.3.4
      - 1.3.5
      - 1.4.0
      - 1.4.1
      - 1.4.2
p-mysql:
  1.5.0:
    upgrades_from:
      - 1.3.2
      - 1.4.0
p-redis:
  1.4.4:
    upgrades_from:
      - 1.4.0
      - 1.4.1
      - 1.4.2
      - 1.4.3